import { Student, Session, User } from '../types';
import { shiftDateString } from './storage';

export const DEMO_USER: User = {
  id: 'demo-local-counselor',
  name: 'Demo Danışman',
  email: 'demo@ornek.k12.tr',
  role: 'Rehber Öğretmen & Psikolojik Danışman',
  school: 'Örnek Anadolu Lisesi',
  phone: '0500 000 00 00',
  created_at: new Date().toISOString(),
  avatar_color: '#0F766E',
  kvkk_accepted: true,
  kvkk_accepted_at: new Date().toISOString(),
};

export function createDemoStudents(): Student[] {
  return [
    {
      id: 'demo-std-1',
      full_name: 'Mehmet Yılmaz',
      class_grade: '12-A',
      phone: '0500 000 00 11',
      last_meeting_date: null,
      status_flags: ['AYT Matematik', 'Deneme Analizi'],
      target_goal: 'Hacettepe Tıp',
      notes: 'Haftalık 400 soru hedefi verildi. Sayısal ilk 5000 hedefliyor.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-2',
      full_name: 'Zeynep Kaya',
      class_grade: '12-B',
      phone: '0500 000 00 12',
      last_meeting_date: null,
      status_flags: ['Paragraf Rutini', 'Sınav Kaygısı'],
      target_goal: 'İstanbul Üniversitesi Hukuk',
      notes: 'Zaman yönetimi teknikleri çalışıldı. Pomodoro tekniği önerildi.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-3',
      full_name: 'Ali Demir',
      class_grade: '11-A',
      phone: '0500 000 00 13',
      last_meeting_date: null,
      status_flags: ['Geometri Eksiği', 'Motivasyon'],
      target_goal: 'İTÜ Bilgisayar Mühendisliği',
      notes: 'Üçgenler fasikülü bitirilecek. Çarşamba günü kontrol edilecek.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-4',
      full_name: 'Elif Şahin',
      class_grade: '11-C',
      phone: '0500 000 00 14',
      last_meeting_date: null,
      status_flags: ['Program Aksatması'],
      target_goal: 'ODTÜ Mimarlık',
      notes: 'Ders çalışma günlüğü oluşturuldu. Haftalık çizelge doldurulacak.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-5',
      full_name: 'Burak Çelik',
      class_grade: '10-B',
      phone: '0500 000 00 15',
      last_meeting_date: null,
      status_flags: ['Zaman Yönetimi'],
      target_goal: 'Yıldız Teknik Endüstri Mühendisliği',
      notes: 'Telefon kullanım süresi kısıtlaması planlandı.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-6',
      full_name: 'Ayşe Yıldız',
      class_grade: '12-C',
      phone: '0500 000 00 16',
      last_meeting_date: null,
      status_flags: ['FKB Çalışması', 'Net Düşüşü'],
      target_goal: 'Ege Diş Hekimliği',
      notes: 'Fizik branş denemelerinde süre takibi yapacak.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-7',
      full_name: 'Emre Öztürk',
      class_grade: '9-A',
      phone: '0500 000 00 17',
      last_meeting_date: null,
      status_flags: ['Motivasyon'],
      target_goal: 'Fen Lisesi Uyum & Sayısal Alan',
      notes: 'Liseye uyum süreci değerlendirildi. Sosyal kulüplere katılımı teşvik edildi.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-8',
      full_name: 'Merve Aydın',
      class_grade: '11-B',
      phone: '0500 000 00 18',
      last_meeting_date: null,
      status_flags: ['Sınav Kaygısı'],
      target_goal: 'Boğaziçi Psikoloji',
      notes: 'Nefes egzersizleri ve olumlu iç diyalog çalışması yapıldı.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-9',
      full_name: 'Can Koç',
      class_grade: '10-A',
      phone: '0500 000 00 19',
      last_meeting_date: null,
      status_flags: ['Kaynak Seçimi'],
      target_goal: 'Yazılım Mühendisliği',
      notes: 'Seviyesine uygun soru bankaları listesi çıkarıldı.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-10',
      full_name: 'Fatma Arslan',
      class_grade: '12-A',
      phone: '0500 000 00 20',
      last_meeting_date: null,
      status_flags: ['Deneme Analizi', 'AYT Matematik'],
      target_goal: 'Ankara Üniversitesi Eczacılık',
      notes: 'Son 3 Türkiye Geneli denemenin yanlış analiz defteri incelendi.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-11',
      full_name: 'Kerem Doğan',
      class_grade: '10-C',
      phone: '0500 000 00 21',
      last_meeting_date: null,
      status_flags: ['Program Aksatması'],
      target_goal: 'Marmara İktisat',
      notes: 'Akşam etüt çalışma saatleri düzenlendi.',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-std-12',
      full_name: 'İrem Aksoy',
      class_grade: '11-A',
      phone: '0500 000 00 22',
      last_meeting_date: null,
      status_flags: ['FKB Çalışması', 'Paragraf Rutini'],
      target_goal: 'Bilkent Moleküler Biyoloji',
      notes: 'Biyoloji sistemler tekrarı ve haftalık deneme takvimi oluşturuldu.',
      created_at: new Date().toISOString(),
    },
  ];
}

export function createDemoSessions(students: Student[], baseDate: string): Session[] {
  const d0 = baseDate; // Today
  const dPrev = shiftDateString(baseDate, -1); // Yesterday
  const dNext1 = shiftDateString(baseDate, 1); // Tomorrow
  const dNext2 = shiftDateString(baseDate, 2); // 2 days ahead

  const sessions: Session[] = [
    // Today's sessions
    {
      id: 'demo-sess-1',
      date: d0,
      time_slot: '09:00',
      student_id: students[0].id,
      topic: 'TYT Matematik Net Analizi',
      action_items: 'Her gün 30 paragraf sorusu + 20 problem',
      tags: ['Deneme Analizi', 'AYT Matematik'],
      status: 'Geldi',
      created_at: new Date().toISOString(),
      feedback: {
        status: 'Geldi',
        submitted_at: new Date().toISOString(),
        rating: 5,
        efficiency: 'Çok Verimli',
        notes: 'Net hedefler netleşti, motivasyonu yüksek.',
        next_step: 'Haftalık soru çizelgesi teslim edilecek.',
      },
    },
    {
      id: 'demo-sess-2',
      date: d0,
      time_slot: '09:40',
      student_id: students[1].id,
      topic: 'Sınav Kaygısı ve Zaman Yönetimi',
      action_items: 'Nefes egzersizi günde 2 kez uygulanacak',
      tags: ['Sınav Kaygısı', 'Paragraf Rutini'],
      status: 'Geldi',
      created_at: new Date().toISOString(),
      feedback: {
        status: 'Geldi',
        submitted_at: new Date().toISOString(),
        rating: 4,
        efficiency: 'Verimli',
        notes: 'Görüşme verimli geçti, kaygı düzeyi azaldı.',
        next_step: 'Deneme öncesi rutin listesi uygulanacak.',
      },
    },
    {
      id: 'demo-sess-3',
      date: d0,
      time_slot: '10:20',
      student_id: null,
      topic: '15 dk Teneffüs',
      action_items: '',
      tags: [],
      status: 'Bekliyor',
      is_break: true,
      break_title: '15 dk Teneffüs',
      break_duration: 15,
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-4',
      date: d0,
      time_slot: '10:40',
      student_id: students[2].id,
      topic: 'Geometri Soru Çözüm Rutini',
      action_items: 'Üçgenler fasikülü bitirilecek',
      tags: ['Geometri Eksiği'],
      status: 'Gelmedi',
      created_at: new Date().toISOString(),
      feedback: {
        status: 'Gelmedi',
        submitted_at: new Date().toISOString(),
        reason: 'Hastalık',
        parent_notified: true,
        makeup_session_planned: true,
        notes: 'Hasta olduğu için gelemedi, veli ile telefonla görüşüldü.',
      },
    },
    {
      id: 'demo-sess-5',
      date: d0,
      time_slot: '11:20',
      student_id: students[3].id,
      topic: 'Haftalık Program Takibi',
      action_items: 'Günlük çalışma çizelgesi tutulacak',
      tags: ['Program Aksatması'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-6',
      date: d0,
      time_slot: '12:00',
      student_id: null,
      topic: '45 dk Öğle Arası & Yemek',
      action_items: '',
      tags: [],
      status: 'Bekliyor',
      is_break: true,
      break_title: '45 dk Öğle Arası & Yemek',
      break_duration: 45,
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-7',
      date: d0,
      time_slot: '13:00',
      student_id: students[4].id,
      topic: 'Ders Çalışma Rutinleri',
      action_items: 'Her akşam 1 saat etüt çalışması',
      tags: ['Zaman Yönetimi'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-8',
      date: d0,
      time_slot: '13:40',
      student_id: students[5].id,
      topic: 'Fen Bilimleri Net Artırma',
      action_items: 'Fizik optik ve dalgalar tekrarı',
      tags: ['FKB Çalışması', 'Net Düşüşü'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-9',
      date: d0,
      time_slot: '14:20',
      student_id: students[6].id,
      topic: '9. Sınıf Uyum Değerlendirmesi',
      action_items: 'Sosyal kulüp seçimi tamamlanacak',
      tags: ['Motivasyon'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },

    // Yesterday's sessions
    {
      id: 'demo-sess-10',
      date: dPrev,
      time_slot: '09:00',
      student_id: students[7].id,
      topic: 'Hedef Belirleme & Motivasyon',
      action_items: 'Hedef üniversite tanıtım videosu izlenecek',
      tags: ['Sınav Kaygısı', 'Motivasyon'],
      status: 'Geldi',
      created_at: new Date().toISOString(),
      feedback: {
        status: 'Geldi',
        submitted_at: new Date().toISOString(),
        rating: 5,
        efficiency: 'Çok Verimli',
        notes: 'Görüşme çok olumlu geçti.',
      },
    },
    {
      id: 'demo-sess-11',
      date: dPrev,
      time_slot: '10:00',
      student_id: students[8].id,
      topic: 'Kaynak Seçimi ve Planlama',
      action_items: 'Seviye tespit testleri tamamlanacak',
      tags: ['Kaynak Seçimi'],
      status: 'Geldi',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-12',
      date: dPrev,
      time_slot: '11:00',
      student_id: students[9].id,
      topic: 'AYT Matematik Soru Dağılımı',
      action_items: 'Türev ve integral soru bankası temini',
      tags: ['AYT Matematik', 'Deneme Analizi'],
      status: 'Geldi',
      created_at: new Date().toISOString(),
    },

    // Tomorrow's sessions
    {
      id: 'demo-sess-13',
      date: dNext1,
      time_slot: '09:00',
      student_id: students[10].id,
      topic: 'Haftalık Program Gözden Geçirme',
      action_items: 'Günlük soru sayıları kontrol edilecek',
      tags: ['Program Aksatması'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-14',
      date: dNext1,
      time_slot: '09:40',
      student_id: students[11].id,
      topic: 'Biyoloji Sistemler Çalışma Planı',
      action_items: 'Dolaşım ve boşaltım sistemi özeti çıkarılacak',
      tags: ['FKB Çalışması'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-15',
      date: dNext1,
      time_slot: '10:20',
      student_id: null,
      topic: '15 dk Teneffüs',
      action_items: '',
      tags: [],
      status: 'Bekliyor',
      is_break: true,
      break_title: '15 dk Teneffüs',
      break_duration: 15,
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-16',
      date: dNext1,
      time_slot: '10:40',
      student_id: students[0].id,
      topic: 'Geometri Deneme Kontrolü',
      action_items: 'Yanlış soruların çözümü incelenecek',
      tags: ['Deneme Analizi'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-17',
      date: dNext1,
      time_slot: '11:20',
      student_id: students[2].id,
      topic: 'Telafi Seansı: Üçgenler',
      action_items: 'Eksik konular tamamlanacak',
      tags: ['Geometri Eksiği'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },

    // Day after tomorrow's sessions
    {
      id: 'demo-sess-18',
      date: dNext2,
      time_slot: '09:30',
      student_id: students[1].id,
      topic: 'Türkçe Paragraf Hızlandırma',
      action_items: 'Her sabah 20 dakika süre tutarak paragraf',
      tags: ['Paragraf Rutini'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-sess-19',
      date: dNext2,
      time_slot: '10:30',
      student_id: students[5].id,
      topic: 'Genel Değerlendirme & Veli İletişimi',
      action_items: 'Veli ile ara karne sonrası görüşme yapılacak',
      tags: ['Net Düşüşü'],
      status: 'Bekliyor',
      created_at: new Date().toISOString(),
    },
  ];

  return sessions;
}
